import './globals.css';

import Header from './components/header/header';
import { didact } from './fonts/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${didact.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
