import './globals.css';
import dynamic from 'next/dynamic';
import Header from './components/header/header';
import { didact } from './fonts/fonts';
const Scene = dynamic(() => import('@/app/components/canvas/scene'), {
  ssr: false,
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={didact.className}>
        <Header />
        {children}
        <Scene />
      </body>
    </html>
  );
}
